name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - requests=2.24.0
  - pip=23.3.1
  - mlflow=2.14.3
  - hydra-core=1.3.2
  - pip:
      - wandb==0.17.5
      - hydra-joblib-launcher==1.1.2
